### ISSUE TITLE
Can't add both /admin and /login to either global ignore list or exclusion for a lang

### ISSUE THREAD

**Issue by zeon** [xfra35/f3-multilang#10]
Hi I am using [fabulog ](https://github.com/ikkez/fabulog) and I can't seem to add both /admin and /login to the global ignore list, can you tell me how do I do that? Below's my config.ini:

menu = about, press, news, terms, privacy, contact, login, admin

[maps]
@about          : /about                        = Controller\About
@press          : /press                        = Controller\Press
@news           : /news                         = Controller\News
@terms          : /terms                        = Controller\Terms
@privacy        : /privacy                      = Controller\Privacy
@contact_add    : /contact/add                  = Controller\Contact->addContact
@contact_alert  : /contact/alert                = Controller\Contact->alert
@image_download : /download/@image              = Controller\Press->imageDownload
@login          : /login                        = Controller\Auth->login
@admin          : /admin                        = Controller\Dashboard->main

[MULTILANG]
global = terms, privacy, /admin/post, contact_add, contact_alert, image_download, login, admin

[MULTILANG.languages]
en = en-GB, en-US, en
tw = zh-TW, tw

[MULTILANG.rules.en]
admin_create = /admin/@module/create
contact_add = /contact/add
contact_alert = /contact/alert
image_download = /download/@image
admin = false
login = false

[MULTILANG.rules.tw]
admin_create = /admin/@module/create
contact_add = /contact/add
contact_alert = /contact/alert
image_download = /download/@image

**Comment by xfra35** [comment]
What are you trying to achieve?

Since you've put `login` and `admin` in the "global" list:
- `/login` and `/admin` will be reachable
- `/en/login` and `/en/admin` will throw a 404
- `/tw/login` and `/tw/admin` will throw a 404

In other words, those 2 routes are excluded from _all_ languages (`/en` and `/tw`).

So the extra rules<sup>[1]</sup> which manually exclude those routes from the English language are useless.

<hr>

<sup>[1]</sup> `MULTILANG.rules.en.admin = false` and `MULTILANG.rules.en.login = false`

**Comment by zeon** [comment]
Yes it supposed exclude but it's not and i get 404 when accessing both:

/login
/admin

and all the pages under /admin

you can give it a try using fabulog.

**Comment by xfra35** [comment]
Hi @zeon,

I've just made a quick test and it works fine. See [here](https://github.com/xfra35/fabulog/commit/dbfd9581b6e5bdc73367aab99e919380db040132) the changes applied to the original fabulog.

Of course, not everything is ready but we have:
- `/en` which displays the listing
- `/en/future-post` which displays a post
- `/login` which shows the login form
- `/admin` and `/admin/*` which manage the dashboard

Hope it helps.
