### ISSUE TITLE
Lang selector as not a part of the URL

### ISSUE THREAD

**Issue by Kekesed** [xfra35/f3-multilang#13]
Hi, i hope that the url format is not `/xx/user` but `/user?lang=xx`.
and then, the `?lang=xx` is can be removed as it was saved into cookie. So user can acces other page on the same Language. 

Eg. `/about` without need to specify `?lang=xx` again after accessing `/user?lang=id` (User no need to access this way: `/about?lang=id`.

Thankyou!!

**Comment by xfra35** [comment]
Hi,
That's not possible with the plugin, as it is focused on producing SEO-friendly multilingual URIs.

But you don't really need a plugin for that case, do you? This should be as easy as including the following snippet in your `index.php`:

``` php
if ($f3->exists('GET.lang'))
  $f3->copy('GET.lang','COOKIE.lang');
if ($f3->exists('COOKIE.lang'))
  $f3->copy('COOKIE.lang','LANGUAGE');
```

Anyway, one day I may refactor the plugin to make it less restrictive.

**Comment by Kekesed** [comment]
hmm looks like so...
And then, i could just use a definition file for the strings? and then include them as language specified? :laughing: :laughing: 

Thanks anyway

**Comment by xfra35** [comment]
If you're talking about localization, F3 handles that already. See [here](http://fatfreeframework.com/base#language). Just set `LOCALES` to the location of your dictionary files.

**Comment by Kekesed** [comment]
ohh yup, i've read it this morning hahha, forgot to close this.
Thanks! You're such a big help!
