### ISSUE TITLE
Rerouting for obsolete pages

### ISSUE THREAD

**Issue by planetahuevo** [xfra35/f3-multilang#15]
Hi, 
I am trying to make this work: 
From here:
http://fatfreeframework.com/routing-engine
`$f3->redirect('GET|HEAD /obsoletepage', '/newpage');`
And the problem is that the obsolete page is not working because it has the language before it. 
/en/obsoletepage
So it does not redirect. 
Any ideas?

Thanks!

**Comment by xfra35** [comment]
Sure:

**Case 1: the new URL slug depends on the language**

``` php
$f3->redirect('GET /en/obsoletepage','/en/newpage');
$f3->redirect('GET /fr/obsoletepage','/fr/nouvelle-page');
```

**Case 2: the new URL slug is the same for all languages**

``` php
$f3->redirect('GET /@lang/obsoletepage','/@lang/newpage');
```

**Comment by planetahuevo** [comment]
Case 2 was my problem!
I forgot about the @lang thing. :+1: Thanks!
