### ISSUE TITLE
Migrate issue with latest F3 changes

### ISSUE THREAD

**Issue by ptdev** [xfra35/f3-multilang#21]
Hey there xfra35,

I've been using this library with the migrate option enabled and recently the redirects began being made to:

/lang/somepath/@someparam

When it previously would redirect to:

/lang/somepath/theactualparam

That is, it redirects to a route without replacing the placeholder with the actual parameter.
Please see the screenshot from devtools where you can see the "Location" header redirecting to a route without substituting the route parameter with the actual variable.

![f3multilang](https://user-images.githubusercontent.com/1280528/73189615-9c932480-411c-11ea-8342-c961d1c82ee3.png)

I'm guessing this is happening since [this change](https://github.com/bcosca/fatfree-core/commit/221f0c930f8664565c9825faeb9ed9af0f7a01c8). At least if I use a base.php file before that I get the correct behavior.

Cheers

**Comment by xfra35** [comment]
Thanks for reporting. I've asked @ikkez what was the rationale behind this change, which will break a lot of code (not only this library). Let's wait for his answer.

**Comment by ptdev** [comment]
Hey, the latest change by @ikkez appears to have fixed it the issue. Thank you both. 🥇 
Closing.
