### ISSUE TITLE
Not all URLs to get multilingual

### ISSUE THREAD

**Issue by rafmst** [xfra35/f3-multilang#3]
Imagine that I have a backoffice, in my backoffice urls I don't want the language prefix to appear. 
For example: 

-Public url:
http://www.example.com/en/contacts
http://www.example.com/pt/contactos
http://www.example.com/en/portfolio
http://www.example.com/pt/portfolio

-Backoffice url:
http://www.example.com/admin/users
http://www.example.com/admin/news
http://www.example.com/admin/configs

**Comment by xfra35** [comment]
Hey @rafaelmoraissantos, good point!

The same as raised in #2. Please see my proposal there.

**Comment by xfra35** [comment]
Hey @rafamds, you can now include prefixes in MULTILANG.global:

``` ini
[MULTILANG]
global = /api, /admin, /path/to/folder
```
