### ISSUE TITLE
Option for turn off rewriting in primary language

### ISSUE THREAD

**Issue by mike1701** [xfra35/f3-multilang#5]
Wish to have this option you have described in the google-group under https://groups.google.com/d/msg/f3-framework/NAhOB6rL6sw/4YpQ4OPT900J

It would be great. 

Thanks

**Comment by xfra35** [comment]
Yep that's on my list. Hopefully I'll find time for it next week.
Cheers

**Comment by xfra35** [comment]
Hi @mike1701, I've added a [migration mode](https://github.com/xfra35/f3-multilang#migration-mode) to the plugin, which automatically redirects old URIs to the new primary language.

I finally favored a redirection as just turning off rewriting raises some other issues (in particular the issue of detecting the language on a non-prefixed URI, be it a global URI or an old URI).

**Comment by mike1701** [comment]
Thanks for this - it works so far, but i have wish a rendering without 301-redirect to the url with language-code. So Searchengines indexing urls without language-iso-code for the primary language and the menu-url-links for primary language are without iso-code. Is there any chance to realize this in any extended migration-mode ?
