### ISSUE TITLE
Will multilang be update to be used with Fatfree v3.5?

### ISSUE THREAD

**Issue by zeon** [xfra35/f3-multilang#7]

**Comment by xfra35** [comment]
Hi @zeon, the plugin is compatible with v3.5. I'll update the repository soon, but you can use it already now.

**Comment by zeon** [comment]
did you mean that I can just replace the base.php file from multi-lang to
the base.php in fatfree v3.5?

**Comment by xfra35** [comment]
Yes exactly.

**Comment by xfra35** [comment]
I've [added](https://github.com/xfra35/f3-multilang/commit/0299e22facdc2f0e84e062df01a677794053d420) support for Composer to make it clear than the plugin is expected to work with the latest framework version.
